apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name}}hello-app
  #namespace: mem-example
spec:
  containers:
  - name: hello-app-ctr
    image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"